import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  {
    path: '',
    redirectTo: 'intro',
    pathMatch: 'full'
  },
  //{
    //path: 'home',
    //loadChildren: './home/home.module#HomePageModule'
    // path: 'items',
    // loadChildren: () => import('./items/items.module').then(m => m.ItemsModule)
  //},
  // {
  //   path: 'list',
  //   loadChildren: './list/list.module#ListPageModule'
  // },
  // For Components
  // { path: 'list-infinte-scroll', loadChildren: './list-infinte-scroll/list-infinte-scroll.module#ListInfinteScrollPageModule' },
  // { path: 'list-refresher', loadChildren: './list-refresher/list-refresher.module#ListRefresherPageModule' },
  // { path: 'list-slide-left', loadChildren: './list-slide-left/list-slide-left.module#ListSlideLeftPageModule' },
  // { path: 'list-slide-right', loadChildren: './list-slide-right/list-slide-right.module#ListSlideRightPageModule' },
  // { path: 'list-fade-in', loadChildren: './list-fade-in/list-fade-in.module#ListFadeInPageModule' },
  // { path: 'list-swipe-thumbnail-products', loadChildren: './list-swipe-thumbnail-products/list-swipe-thumbnail-products.module#ListSwipeThumbnailProductsPageModule' },
  // { path: 'list-swipe-full-image', loadChildren: './list-swipe-full-image/list-swipe-full-image.module#ListSwipeFullImagePageModule' },
  // { path: 'list-swipe-with-header', loadChildren: './list-swipe-with-header/list-swipe-with-header.module#ListSwipeWithHeaderPageModule' },
  // { path: 'list-swipe-left-to-right', loadChildren: './list-swipe-left-to-right/list-swipe-left-to-right.module#ListSwipeLeftToRightPageModule' },
  // { path: 'list-swipe-right-to-left', loadChildren: './list-swipe-right-to-left/list-swipe-right-to-left.module#ListSwipeRightToLeftPageModule' },
  // { path: 'list-reorder', loadChildren: './list-reorder/list-reorder.module#ListReorderPageModule' },
  // { path: 'list-expandable', loadChildren: './list-expandable/list-expandable.module#ListExpandablePageModule' },
  // { path: 'grid-two-line', loadChildren: './grid-two-line/grid-two-line.module#GridTwoLinePageModule' },
  // { path: 'grid-three-line', loadChildren: './grid-three-line/grid-three-line.module#GridThreeLinePageModule' },
  // { path: 'grid-category', loadChildren: './grid-category/grid-category.module#GridCategoryPageModule' },
  // { path: 'grid-subcategory', loadChildren: './grid-subcategory/grid-subcategory.module#GridSubcategoryPageModule' },
  // { path: 'grid-album', loadChildren: './grid-album/grid-album.module#GridAlbumPageModule' },
  // { path: 'grid-section', loadChildren: './grid-section/grid-section.module#GridSectionPageModule' },
  // { path: 'grid-with-header', loadChildren: './grid-with-header/grid-with-header.module#GridWithHeaderPageModule' },
  // { path: 'card-dashboard', loadChildren: './card-dashboard/card-dashboard.module#CardDashboardPageModule' },
  // { path: 'card-list-simple', loadChildren: './card-list-simple/card-list-simple.module#CardListSimplePageModule' },
  // { path: 'card-list-avatar', loadChildren: './card-list-avatar/card-list-avatar.module#CardListAvatarPageModule' },
  // { path: 'card-shoping-simple', loadChildren: './card-shoping-simple/card-shoping-simple.module#CardShopingSimplePageModule' },
  // { path: 'card-shoping-slider', loadChildren: './card-shoping-slider/card-shoping-slider.module#CardShopingSliderPageModule' },
  // { path: 'card-timeline-theme-one', loadChildren: './card-timeline-theme-one/card-timeline-theme-one.module#CardTimelineThemeOnePageModule' },
  // { path: 'card-timeline-theme-two', loadChildren: './card-timeline-theme-two/card-timeline-theme-two.module#CardTimelineThemeTwoPageModule' },
  // { path: 'card-timeline-theme-three', loadChildren: './card-timeline-theme-three/card-timeline-theme-three.module#CardTimelineThemeThreePageModule' },
  // { path: 'card-images', loadChildren: './card-images/card-images.module#CardImagesPageModule' },
  // { path: 'slider-simple', loadChildren: './slider-simple/slider-simple.module#SliderSimplePageModule' },
  // { path: 'slider-images', loadChildren: './slider-images/slider-images.module#SliderImagesPageModule' },
  // { path: 'slider-autoplay', loadChildren: './slider-autoplay/slider-autoplay.module#SliderAutoplayPageModule' },
  // { path: 'slider-arrows', loadChildren: './slider-arrows/slider-arrows.module#SliderArrowsPageModule' },
  // { path: 'tab-footer-text', loadChildren: './tab-footer-text/tab-footer-text.module#TabFooterTextPageModule' },
  // { path: 'tab-footer-icon', loadChildren: './tab-footer-icon/tab-footer-icon.module#TabFooterIconPageModule' },
  // { path: 'tab-footer-text-icon', loadChildren: './tab-footer-text-icon/tab-footer-text-icon.module#TabFooterTextIconPageModule' },
  // { path: 'tab-footer-text-icon-badge', loadChildren: './tab-footer-text-icon-badge/tab-footer-text-icon-badge.module#TabFooterTextIconBadgePageModule' },
  // { path: 'tab-header-text', loadChildren: './tab-header-text/tab-header-text.module#TabHeaderTextPageModule' },
  // { path: 'tab-header-icon', loadChildren: './tab-header-icon/tab-header-icon.module#TabHeaderIconPageModule' },
  // { path: 'tab-header-text-icon', loadChildren: './tab-header-text-icon/tab-header-text-icon.module#TabHeaderTextIconPageModule' },
  // { path: 'tab-header-text-icon-badge', loadChildren: './tab-header-text-icon-badge/tab-header-text-icon-badge.module#TabHeaderTextIconBadgePageModule' },
  // { path: 'segment-header-text', loadChildren: './segment-header-text/segment-header-text.module#SegmentHeaderTextPageModule' },
  // { path: 'segment-header-icon', loadChildren: './segment-header-icon/segment-header-icon.module#SegmentHeaderIconPageModule' },
  // { path: 'segment-scrollable-header-text', loadChildren: './segment-scrollable-header-text/segment-scrollable-header-text.module#SegmentScrollableHeaderTextPageModule' },
  // { path: 'segment-scrollable-header-icon', loadChildren: './segment-scrollable-header-icon/segment-scrollable-header-icon.module#SegmentScrollableHeaderIconPageModule' },
  // { path: 'segment-footer-text', loadChildren: './segment-footer-text/segment-footer-text.module#SegmentFooterTextPageModule' },
  // { path: 'segment-footer-icon', loadChildren: './segment-footer-icon/segment-footer-icon.module#SegmentFooterIconPageModule' },
  // { path: 'segment-footer-text-icon', loadChildren: './segment-footer-text-icon/segment-footer-text-icon.module#SegmentFooterTextIconPageModule' },
  // { path: 'button-basic-one', loadChildren: './button-basic-one/button-basic-one.module#ButtonBasicOnePageModule' },
  // { path: 'button-basic-two', loadChildren: './button-basic-two/button-basic-two.module#ButtonBasicTwoPageModule' },
  // { path: 'button-text', loadChildren: './button-text/button-text.module#ButtonTextPageModule' },
  // { path: 'button-outline', loadChildren: './button-outline/button-outline.module#ButtonOutlinePageModule' },
  // { path: 'button-transparent', loadChildren: './button-transparent/button-transparent.module#ButtonTransparentPageModule' },
  // { path: 'button-expand', loadChildren: './button-expand/button-expand.module#ButtonExpandPageModule' },
  // { path: 'radio-simple-left', loadChildren: './radio-simple-left/radio-simple-left.module#RadioSimpleLeftPageModule' },
  // { path: 'radio-simple-right', loadChildren: './radio-simple-right/radio-simple-right.module#RadioSimpleRightPageModule' },
  // { path: 'radio-circle-with-avatar', loadChildren: './radio-circle-with-avatar/radio-circle-with-avatar.module#RadioCircleWithAvatarPageModule' },
  // { path: 'radio-square-with-big-image', loadChildren: './radio-square-with-big-image/radio-square-with-big-image.module#RadioSquareWithBigImagePageModule' },
  // { path: 'checkbox-simple', loadChildren: './checkbox-simple/checkbox-simple.module#CheckboxSimplePageModule' },
  // { path: 'checkbox-square', loadChildren: './checkbox-square/checkbox-square.module#CheckboxSquarePageModule' },
  // { path: 'checkbox-right-with-avatar', loadChildren: './checkbox-right-with-avatar/checkbox-right-with-avatar.module#CheckboxRightWithAvatarPageModule' },
  // { path: 'checkbox-with-big-image', loadChildren: './checkbox-with-big-image/checkbox-with-big-image.module#CheckboxWithBigImagePageModule' },
  // { path: 'badge-with-card', loadChildren: './badge-with-card/badge-with-card.module#BadgeWithCardPageModule' },
  // { path: 'badge-with-tab', loadChildren: './badge-with-tab/badge-with-tab.module#BadgeWithTabPageModule' },
  // { path: 'badge-with-list', loadChildren: './badge-with-list/badge-with-list.module#BadgeWithListPageModule' },
  // { path: 'toggle-with-avatar', loadChildren: './toggle-with-avatar/toggle-with-avatar.module#ToggleWithAvatarPageModule' },
  // { path: 'toggle-simple-left', loadChildren: './toggle-simple-left/toggle-simple-left.module#ToggleSimpleLeftPageModule' },
  // { path: 'searchbar-simple', loadChildren: './searchbar-simple/searchbar-simple.module#SearchbarSimplePageModule' },
  // { path: 'searchbar-with-images', loadChildren: './searchbar-with-images/searchbar-with-images.module#SearchbarWithImagesPageModule' },
  // { path: 'fab-simple-text', loadChildren: './fab-simple-text/fab-simple-text.module#FabSimpleTextPageModule' },
  // { path: 'fab-simple-icon', loadChildren: './fab-simple-icon/fab-simple-icon.module#FabSimpleIconPageModule' },
  // { path: 'fab-up-text', loadChildren: './fab-up-text/fab-up-text.module#FabUpTextPageModule' },
  // { path: 'fab-up-icon', loadChildren: './fab-up-icon/fab-up-icon.module#FabUpIconPageModule' },
  // { path: 'fab-down-text', loadChildren: './fab-down-text/fab-down-text.module#FabDownTextPageModule' },
  // { path: 'fab-down-icon', loadChildren: './fab-down-icon/fab-down-icon.module#FabDownIconPageModule' },
  // { path: 'fab-left-text', loadChildren: './fab-left-text/fab-left-text.module#FabLeftTextPageModule' },
  // { path: 'fab-left-icon', loadChildren: './fab-left-icon/fab-left-icon.module#FabLeftIconPageModule' },
  // { path: 'fab-right-text', loadChildren: './fab-right-text/fab-right-text.module#FabRightTextPageModule' },
  // { path: 'fab-right-icon', loadChildren: './fab-right-icon/fab-right-icon.module#FabRightIconPageModule' },
  // { path: 'fab-middle-text', loadChildren: './fab-middle-text/fab-middle-text.module#FabMiddleTextPageModule' },
  // { path: 'fab-middle-icon', loadChildren: './fab-middle-icon/fab-middle-icon.module#FabMiddleIconPageModule' },
  // { path: 'alert-basic', loadChildren: './alert-basic/alert-basic.module#AlertBasicPageModule' },
  // { path: 'alert-confirmation', loadChildren: './alert-confirmation/alert-confirmation.module#AlertConfirmationPageModule' },
  // { path: 'alert-prompt', loadChildren: './alert-prompt/alert-prompt.module#AlertPromptPageModule' },
  // { path: 'alert-radio', loadChildren: './alert-radio/alert-radio.module#AlertRadioPageModule' },
  // { path: 'alert-checkbox', loadChildren: './alert-checkbox/alert-checkbox.module#AlertCheckboxPageModule' },
  // { path: 'toast-bottom', loadChildren: './toast-bottom/toast-bottom.module#ToastBottomPageModule' },
  // { path: 'toast-middle', loadChildren: './toast-middle/toast-middle.module#ToastMiddlePageModule' },
  // { path: 'toast-top', loadChildren: './toast-top/toast-top.module#ToastTopPageModule' },
  // { path: 'actionsheet-simple', loadChildren: './actionsheet-simple/actionsheet-simple.module#ActionsheetSimplePageModule' },
  // { path: 'actionsheet-icon', loadChildren: './actionsheet-icon/actionsheet-icon.module#ActionsheetIconPageModule' },
  // { path: 'parallax-header-image', loadChildren: './parallax-header-image/parallax-header-image.module#ParallaxHeaderImagePageModule' },
  // { path: 'form-login-one', loadChildren: './form-login-one/form-login-one.module#FormLoginOnePageModule' },
  // { path: 'form-login-two', loadChildren: './form-login-two/form-login-two.module#FormLoginTwoPageModule' },
  // { path: 'form-login-three', loadChildren: './form-login-three/form-login-three.module#FormLoginThreePageModule' },
  // { path: 'form-register-one', loadChildren: './form-register-one/form-register-one.module#FormRegisterOnePageModule' },
  // { path: 'form-register-two', loadChildren: './form-register-two/form-register-two.module#FormRegisterTwoPageModule' },
  // { path: 'form-register-three', loadChildren: './form-register-three/form-register-three.module#FormRegisterThreePageModule' },
  // { path: 'grid-slider', loadChildren: './grid-slider/grid-slider.module#GridSliderPageModule' },
  // { path: 'grid-subcategory-two', loadChildren: './grid-subcategory-two/grid-subcategory-two.module#GridSubcategoryTwoPageModule' },
  // { path: 'tab-chat', loadChildren: './tab-chat/tab-chat.module#TabChatPageModule' },
  // { path: 'tab-status', loadChildren: './tab-status/tab-status.module#TabStatusPageModule' },
  // { path: 'tab-call', loadChildren: './tab-call/tab-call.module#TabCallPageModule' },
  // { path: 'badge-movie', loadChildren: './badge-movie/badge-movie.module#BadgeMoviePageModule' },
  // { path: 'badge-card', loadChildren: './badge-card/badge-card.module#BadgeCardPageModule' },
  // { path: 'badge-setting', loadChildren: './badge-setting/badge-setting.module#BadgeSettingPageModule' },
  // { path: 'component-details', loadChildren: './component-details/component-details.module#ComponentDetailsPageModule' },
  //{ path: 'intro', loadChildren: './intro/intro.module#IntroPageModule' },
  //{ path: 'intro', loadChildren:  './i-becrux-bottom/Pages/intro/intro.module#IntroPageModule'  },
  { path: 'intro', loadChildren: './i-becrux-bottom/Pages/home-pages/home/home.module#HomePageModule' },
  // { path: 'form-forget-one', loadChildren: './form-forget-one/form-forget-one.module#FormForgetOnePageModule' },
  // { path: 'form-forget-two', loadChildren: './form-forget-two/form-forget-two.module#FormForgetTwoPageModule' },
  // { path: 'form-forget-three', loadChildren: './form-forget-three/form-forget-three.module#FormForgetThreePageModule' },
  // { path: 'ui-templates-details', loadChildren: './ui-templates-details/ui-templates-details.module#UiTemplatesDetailsPageModule' },

  // For Becrux Sidemenu Paths
  // { path: 'bs-about-us', loadChildren: './i-becrux-side/Pages/about-us/about-us.module#AboutUsPageModule' },
  // { path: 'bs-add-review', loadChildren: './i-becrux-side/Pages/add-review/add-review.module#AddReviewPageModule' },
  // { path: 'bs-cart', loadChildren: './i-becrux-side/Pages/cart/cart.module#CartPageModule' },
  // { path: 'bs-contact-us', loadChildren: './i-becrux-side/Pages/contact-us/contact-us.module#ContactUsPageModule' },
  // { path: 'bs-currency-list', loadChildren: './i-becrux-side/Pages/currency-list/currency-list.module#CurrencyListPageModule' },
  // { path: 'bs-downloads', loadChildren: './i-becrux-side/Pages/downloads/downloads.module#DownloadsPageModule' },
  // { path: 'bs-forgot-password', loadChildren: './i-becrux-side/Pages/forgot-password/forgot-password.module#ForgotPasswordPageModule' },
  // { path: 'bs-intro', loadChildren: './i-becrux-side/Pages/intro/intro.module#IntroPageModule' },
  // { path: 'bs-language', loadChildren: './i-becrux-side/Pages/language/language.module#LanguagePageModule' },
  // { path: 'bs-login', loadChildren: './i-becrux-side/Pages/login/login.module#LoginPageModule' },
  // { path: 'bs-my-account', loadChildren: './i-becrux-side/Pages/my-account/my-account.module#MyAccountPageModule' },
  // { path: 'bs-my-orders', loadChildren: './i-becrux-side/Pages/my-orders/my-orders.module#MyOrdersPageModule' },
  // { path: 'bs-news', loadChildren: './i-becrux-side/Pages/news/news.module#NewsPageModule' },
  // { path: 'bs-news-detail', loadChildren: './i-becrux-side/Pages/news-detail/news-detail.module#NewsDetailPageModule' },
  // { path: 'bs-news-list', loadChildren: './i-becrux-side/Pages/news-list/news-list.module#NewsListPageModule' },
  // { path: 'bs-notifications', loadChildren: './i-becrux-side/Pages/notifications/notifications.module#NotificationsPageModule' },
  // { path: 'bs-order', loadChildren: './i-becrux-side/Pages/order/order.module#OrderPageModule' },
  // { path: 'bs-order-detail', loadChildren: './i-becrux-side/Pages/order-detail/order-detail.module#OrderDetailPageModule' },
  // { path: 'bs-privacy-policy', loadChildren: './i-becrux-side/Pages/privacy-policy/privacy-policy.module#PrivacyPolicyPageModule' },
  // { path: 'bs-product-detail', loadChildren: './i-becrux-side/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'bs-products', loadChildren: './i-becrux-side/Pages/products/products.module#ProductsPageModule' },
  // { path: 'bs-refund-policy', loadChildren: './i-becrux-side/Pages/refund-policy/refund-policy.module#RefundPolicyPageModule' },
  // { path: 'bs-reviews', loadChildren: './i-becrux-side/Pages/reviews/reviews.module#ReviewsPageModule' },
  // { path: 'bs-reward-points', loadChildren: './i-becrux-side/Pages/reward-points/reward-points.module#RewardPointsPageModule' },
  // { path: 'bs-scratch-card', loadChildren: './i-becrux-side/Pages/scratch-card/scratch-card.module#ScratchCardPageModule' },
  // { path: 'bs-search', loadChildren: './i-becrux-side/Pages/search/search.module#SearchPageModule' },
  // { path: 'bs-select-country', loadChildren: './i-becrux-side/Pages/select-country/select-country.module#SelectCountryPageModule' },
  // { path: 'bs-select-zones', loadChildren: './i-becrux-side/Pages/select-zones/select-zones.module#SelectZonesPageModule' },
  // { path: 'bs-settings', loadChildren: './i-becrux-side/Pages/settings/settings.module#SettingsPageModule' },
  // { path: 'bs-shipping-method', loadChildren: './i-becrux-side/Pages/shipping-method/shipping-method.module#ShippingMethodPageModule' },
  // { path: 'bs-sign-up', loadChildren: './i-becrux-side/Pages/sign-up/sign-up.module#SignUpPageModule' },
  // { path: 'bs-store', loadChildren: './i-becrux-side/Pages/store/store.module#StorePageModule' },
  // { path: 'bs-term-services', loadChildren: './i-becrux-side/Pages/term-services/term-services.module#TermServicesPageModule' },
  // { path: 'bs-thank-you', loadChildren: './i-becrux-side/Pages/thank-you/thank-you.module#ThankYouPageModule' },
  // { path: 'bs-wish-list', loadChildren: './i-becrux-side/Pages/wish-list/wish-list.module#WishListPageModule' },
  // { path: 'bs-addresses', loadChildren: './i-becrux-side/Pages/address-pages/addresses/addresses.module#AddressesPageModule' },
  // { path: 'bs-billing-address', loadChildren: './i-becrux-side/Pages/address-pages/billing-address/billing-address.module#BillingAddressPageModule' },
  // { path: 'bs-shipping-address', loadChildren: './i-becrux-side/Pages/address-pages/shipping-address/shipping-address.module#ShippingAddressPageModule' },
  // { path: 'bs-categories', loadChildren: './i-becrux-side/Pages/categorie-pages/categories/categories.module#CategoriesPageModule' },
  // { path: 'bs-categories2', loadChildren: './i-becrux-side/Pages/categorie-pages/categories2/categories2.module#Categories2PageModule' },
  // { path: 'bs-categories3', loadChildren: './i-becrux-side/Pages/categorie-pages/categories3/categories3.module#Categories3PageModule' },
  // { path: 'bs-categories4', loadChildren: './i-becrux-side/Pages/categorie-pages/categories4/categories4.module#Categories4PageModule' },
  // { path: 'bs-categories5', loadChildren: './i-becrux-side/Pages/categorie-pages/categories5/categories5.module#Categories5PageModule' },
  // { path: 'bs-categories6', loadChildren: './i-becrux-side/Pages/categorie-pages/categories6/categories6.module#Categories6PageModule' },
  // { path: 'bs-sub-categories', loadChildren: './i-becrux-side/Pages/categorie-pages/sub-categories/sub-categories.module#SubCategoriesPageModule' },
  // { path: 'bs-sub-categories2', loadChildren: './i-becrux-side/Pages/categorie-pages/sub-categories2/sub-categories2.module#SubCategories2PageModule' },
  // { path: 'bs-sub-categories3', loadChildren: './i-becrux-side/Pages/categorie-pages/sub-categories3/sub-categories3.module#SubCategories3PageModule' },
  // { path: 'bs-sub-categories4', loadChildren: './i-becrux-side/Pages/categorie-pages/sub-categories4/sub-categories4.module#SubCategories4PageModule' },
  // { path: 'bs-sub-categories5', loadChildren: './i-becrux-side/Pages/categorie-pages/sub-categories5/sub-categories5.module#SubCategories5PageModule' },
  // { path: 'bs-sub-categories6', loadChildren: './i-becrux-side/Pages/categorie-pages/sub-categories6/sub-categories6.module#SubCategories6PageModule' },
  // { path: 'bs-home', loadChildren: './i-becrux-side/Pages/home-pages/home/home.module#HomePageModule' },
  // { path: 'bs-home2', loadChildren: './i-becrux-side/Pages/home-pages/home2/home2.module#Home2PageModule' },
  // { path: 'bs-home3', loadChildren: './i-becrux-side/Pages/home-pages/home3/home3.module#Home3PageModule' },
  // { path: 'bs-home4', loadChildren: './i-becrux-side/Pages/home-pages/home4/home4.module#Home4PageModule' },
  // { path: 'bs-home5', loadChildren: './i-becrux-side/Pages/home-pages/home5/home5.module#Home5PageModule' },
  // { path: 'bs-home6', loadChildren: './i-becrux-side/Pages/home-pages/home6/home6.module#Home6PageModule' },
  // { path: 'bs-home7', loadChildren: './i-becrux-side/Pages/home-pages/home7/home7.module#Home7PageModule' },
  // { path: 'bs-home8', loadChildren: './i-becrux-side/Pages/home-pages/home8/home8.module#Home8PageModule' },
  // { path: 'bs-home9', loadChildren: './i-becrux-side/Pages/home-pages/home9/home9.module#Home9PageModule' },
  // { path: 'bs-home10', loadChildren: './i-becrux-side/Pages/home-pages/home10/home10.module#Home10PageModule' },
  // { path: 'bs-color-theme', loadChildren: './i-becrux-side/Pages/color-theme/color-theme.module#ColorThemePageModule' },

  // For Becrux Bottom Paths
  // { path: 'bb-about-us', loadChildren: './i-becrux-bottom/Pages/about-us/about-us.module#AboutUsPageModule' },
  // { path: 'bb-add-review', loadChildren: './i-becrux-bottom/Pages/add-review/add-review.module#AddReviewPageModule' },
  // { path: 'bb-cart', loadChildren: './i-becrux-bottom/Pages/cart/cart.module#CartPageModule' },
   { path: 'bb-contact-us', loadChildren: './i-becrux-bottom/Pages/contact-us/contact-us.module#ContactUsPageModule' },
  // { path: 'bb-currency-list', loadChildren: './i-becrux-bottom/Pages/currency-list/currency-list.module#CurrencyListPageModule' },
  // { path: 'bb-downloads', loadChildren: './i-becrux-bottom/Pages/downloads/downloads.module#DownloadsPageModule' },
  // { path: 'bb-forgot-password', loadChildren: './i-becrux-bottom/Pages/forgot-password/forgot-password.module#ForgotPasswordPageModule' },
  // { path: 'bb-intro', loadChildren: './i-becrux-bottom/Pages/intro/intro.module#IntroPageModule' },
  // { path: 'bb-language', loadChildren: './i-becrux-bottom/Pages/language/language.module#LanguagePageModule' },
  // { path: 'bb-login', loadChildren: './i-becrux-bottom/Pages/login/login.module#LoginPageModule' },
  // { path: 'bb-my-account', loadChildren: './i-becrux-bottom/Pages/my-account/my-account.module#MyAccountPageModule' },
  // { path: 'bb-my-orders', loadChildren: './i-becrux-bottom/Pages/my-orders/my-orders.module#MyOrdersPageModule' },
  // { path: 'bb-news', loadChildren: './i-becrux-bottom/Pages/news/news.module#NewsPageModule' },
  // { path: 'bb-news-detail', loadChildren: './i-becrux-bottom/Pages/news-detail/news-detail.module#NewsDetailPageModule' },
  // { path: 'bb-news-list', loadChildren: './i-becrux-bottom/Pages/news-list/news-list.module#NewsListPageModule' },
  // { path: 'bb-notifications', loadChildren: './i-becrux-bottom/Pages/notifications/notifications.module#NotificationsPageModule' },
  // { path: 'bb-order', loadChildren: './i-becrux-bottom/Pages/order/order.module#OrderPageModule' },
  // { path: 'bb-order-detail', loadChildren: './i-becrux-bottom/Pages/order-detail/order-detail.module#OrderDetailPageModule' },
  // { path: 'bb-privacy-policy', loadChildren: './i-becrux-bottom/Pages/privacy-policy/privacy-policy.module#PrivacyPolicyPageModule' },
   { path: 'bb-product-detail', loadChildren: './i-becrux-bottom/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
   { path: 'bb-product-detail/:id', loadChildren: './i-becrux-bottom/Pages/product-detail/product-detail.module#ProductDetailPageModule'},
   { path: 'bb-products', loadChildren: './i-becrux-bottom/Pages/products/products.module#ProductsPageModule' },
  // { path: 'bb-refund-policy', loadChildren: './i-becrux-bottom/Pages/refund-policy/refund-policy.module#RefundPolicyPageModule' },
  // { path: 'bb-reviews', loadChildren: './i-becrux-bottom/Pages/reviews/reviews.module#ReviewsPageModule' },
  // { path: 'bb-reward-points', loadChildren: './i-becrux-bottom/Pages/reward-points/reward-points.module#RewardPointsPageModule' },
  // { path: 'bb-scratch-card', loadChildren: './i-becrux-bottom/Pages/scratch-card/scratch-card.module#ScratchCardPageModule' },
   { path: 'bb-search', loadChildren: './i-becrux-bottom/Pages/search/search.module#SearchPageModule' },
  // { path: 'bb-select-country', loadChildren: './i-becrux-bottom/Pages/select-country/select-country.module#SelectCountryPageModule' },
  // { path: 'bb-select-zones', loadChildren: './i-becrux-bottom/Pages/select-zones/select-zones.module#SelectZonesPageModule' },
  // { path: 'bb-settings', loadChildren: './i-becrux-bottom/Pages/settings/settings.module#SettingsPageModule' },
  // { path: 'bb-shipping-method', loadChildren: './i-becrux-bottom/Pages/shipping-method/shipping-method.module#ShippingMethodPageModule' },
  // { path: 'bb-sign-up', loadChildren: './i-becrux-bottom/Pages/sign-up/sign-up.module#SignUpPageModule' },
  // { path: 'bb-store', loadChildren: './i-becrux-bottom/Pages/store/store.module#StorePageModule' },
  // { path: 'bb-term-services', loadChildren: './i-becrux-bottom/Pages/term-services/term-services.module#TermServicesPageModule' },
  // { path: 'bb-thank-you', loadChildren: './i-becrux-bottom/Pages/thank-you/thank-you.module#ThankYouPageModule' },
  // { path: 'bb-wish-list', loadChildren: './i-becrux-bottom/Pages/wish-list/wish-list.module#WishListPageModule' },
  // { path: 'bb-addresses', loadChildren: './i-becrux-bottom/Pages/address-pages/addresses/addresses.module#AddressesPageModule' },
  // { path: 'bb-billing-address', loadChildren: './i-becrux-bottom/Pages/address-pages/billing-address/billing-address.module#BillingAddressPageModule' },
  // { path: 'bb-shipping-address', loadChildren: './i-becrux-bottom/Pages/address-pages/shipping-address/shipping-address.module#ShippingAddressPageModule' },
  // { path: 'bb-categories', loadChildren: './i-becrux-bottom/Pages/categorie-pages/categories/categories.module#CategoriesPageModule' },
  // { path: 'bb-categories2', loadChildren: './i-becrux-bottom/Pages/categorie-pages/categories2/categories2.module#Categories2PageModule' },
  // { path: 'bb-categories3', loadChildren: './i-becrux-bottom/Pages/categorie-pages/categories3/categories3.module#Categories3PageModule' },
  // { path: 'bb-categories4', loadChildren: './i-becrux-bottom/Pages/categorie-pages/categories4/categories4.module#Categories4PageModule' },
  // { path: 'bb-categories5', loadChildren: './i-becrux-bottom/Pages/categorie-pages/categories5/categories5.module#Categories5PageModule' },
  // { path: 'bb-categories6', loadChildren: './i-becrux-bottom/Pages/categorie-pages/categories6/categories6.module#Categories6PageModule' },
  // { path: 'bb-sub-categories', loadChildren: './i-becrux-bottom/Pages/categorie-pages/sub-categories/sub-categories.module#SubCategoriesPageModule' },
  // { path: 'bb-sub-categories2', loadChildren: './i-becrux-bottom/Pages/categorie-pages/sub-categories2/sub-categories2.module#SubCategories2PageModule' },
  // { path: 'bb-sub-categories3', loadChildren: './i-becrux-bottom/Pages/categorie-pages/sub-categories3/sub-categories3.module#SubCategories3PageModule' },
  // { path: 'bb-sub-categories4', loadChildren: './i-becrux-bottom/Pages/categorie-pages/sub-categories4/sub-categories4.module#SubCategories4PageModule' },
  // { path: 'bb-sub-categories5', loadChildren: './i-becrux-bottom/Pages/categorie-pages/sub-categories5/sub-categories5.module#SubCategories5PageModule' },
  // { path: 'bb-sub-categories6', loadChildren: './i-becrux-bottom/Pages/categorie-pages/sub-categories6/sub-categories6.module#SubCategories6PageModule' },
   { path: 'bb-home', loadChildren: './i-becrux-bottom/Pages/home-pages/home/home.module#HomePageModule' },
  // { path: 'bb-home2', loadChildren: './i-becrux-bottom/Pages/home-pages/home2/home2.module#Home2PageModule' },
  // { path: 'bb-home3', loadChildren: './i-becrux-bottom/Pages/home-pages/home3/home3.module#Home3PageModule' },
  // { path: 'bb-home4', loadChildren: './i-becrux-bottom/Pages/home-pages/home4/home4.module#Home4PageModule' },
  // { path: 'bb-home5', loadChildren: './i-becrux-bottom/Pages/home-pages/home5/home5.module#Home5PageModule' },
  // { path: 'bb-home6', loadChildren: './i-becrux-bottom/Pages/home-pages/home6/home6.module#Home6PageModule' },
  // { path: 'bb-home7', loadChildren: './i-becrux-bottom/Pages/home-pages/home7/home7.module#Home7PageModule' },
  // { path: 'bb-home8', loadChildren: './i-becrux-bottom/Pages/home-pages/home8/home8.module#Home8PageModule' },
  // { path: 'bb-home9', loadChildren: './i-becrux-bottom/Pages/home-pages/home9/home9.module#Home9PageModule' },
  // { path: 'bb-home10', loadChildren: './i-becrux-bottom/Pages/home-pages/home10/home10.module#Home10PageModule' },
  // { path: 'bb-color-theme', loadChildren: './i-becrux-bottom/Pages/color-theme/color-theme.module#ColorThemePageModule' },
  // { path: 'bb-advance-options', loadChildren: './i-becrux-bottom/Pages/advance-options/advance-options.module#AdvanceOptionsPageModule' },
  // { path: 'bb-setting-ori', loadChildren: './i-becrux-bottom/Pages/setting-ori/setting-ori.module#SettingOriPageModule' },

  // For Lesath Sidemenu Paths
  // {
  //   path: 'ls-home', loadChildren: './i-lesath-side/Pages/home/home.module#HomePageModule'
  // },
  // { path: 'ls-sign-up', loadChildren: './i-lesath-side/Pages/sign-up/sign-up.module#SignUpPageModule' },
  // { path: 'ls-sign-in', loadChildren: './i-lesath-side/Pages/sign-in/sign-in.module#SignInPageModule' },
  // { path: 'ls-forgot-password', loadChildren: './i-lesath-side/Pages/forgot-password/forgot-password.module#ForgotPasswordPageModule' },
  // { path: 'ls-my-account', loadChildren: './i-lesath-side/Pages/my-account/my-account.module#MyAccountPageModule' },
  // { path: 'ls-contact-us', loadChildren: './i-lesath-side/Pages/contact-us/contact-us.module#ContactUsPageModule' },
  // { path: 'ls-search', loadChildren: './i-lesath-side/Pages/search/search.module#SearchPageModule' },
  // { path: 'ls-cart', loadChildren: './i-lesath-side/Pages/cart/cart.module#CartPageModule' },
  // { path: 'ls-my-order', loadChildren: './i-lesath-side/Pages/my-order/my-order.module#MyOrderPageModule' },
  // { path: 'ls-order-details', loadChildren: './i-lesath-side/Pages/order-details/order-details.module#OrderDetailsPageModule' },
  // { path: 'ls-wishlist', loadChildren: './i-lesath-side/Pages/wishlist/wishlist.module#WishlistPageModule' },
  // { path: 'ls-product-detail', loadChildren: './i-lesath-side/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'ls-shipping', loadChildren: './i-lesath-side/Pages/shipping/shipping.module#ShippingPageModule' },
  // { path: 'ls-filter', loadChildren: './i-lesath-side/Pages/filter/filter.module#FilterPageModule' },
  // { path: 'ls-image', loadChildren: './i-lesath-side/Pages/image/image.module#ImagePageModule' },
  // { path: 'ls-thank-you', loadChildren: './i-lesath-side/Pages/thank-you/thank-you.module#ThankYouPageModule' },
  // { path: 'ls-intro', loadChildren: './i-lesath-side/Pages/intro/intro.module#IntroPageModule' },
  // { path: 'ls-sub-category', loadChildren: './i-lesath-side/Pages/sub-category/sub-category.module#SubCategoryPageModule' },
  // { path: 'ls-color-theme', loadChildren: './i-lesath-side/Pages/color-theme/color-theme.module#ColorThemePageModule' },
  // { path: 'ls-privacy-policy', loadChildren: './i-lesath-side/Pages/privacy-policy/privacy-policy.module#PrivacyPolicyPageModule' },
  // { path: 'ls-refund-policy', loadChildren: './i-lesath-side/Pages/refund-policy/refund-policy.module#RefundPolicyPageModule' },
  // { path: 'ls-term-services', loadChildren: './i-lesath-side/Pages/term-services/term-services.module#TermServicesPageModule' },


  // For Lesath Bottom Paths
  // {
  //   path: 'lb-home',
  //   loadChildren: './i-lesath-bottom/Pages/home/home.module#HomePageModule'
  // },
  // { path: 'lb-sign-up', loadChildren: './i-lesath-bottom/Pages/sign-up/sign-up.module#SignUpPageModule' },
  // { path: 'lb-sign-in', loadChildren: './i-lesath-bottom/Pages/sign-in/sign-in.module#SignInPageModule' },
  // { path: 'lb-forgot-password', loadChildren: './i-lesath-bottom/Pages/forgot-password/forgot-password.module#ForgotPasswordPageModule' },
  // { path: 'lb-my-account', loadChildren: './i-lesath-bottom/Pages/my-account/my-account.module#MyAccountPageModule' },
  // { path: 'lb-contact-us', loadChildren: './i-lesath-bottom/Pages/contact-us/contact-us.module#ContactUsPageModule' },
  // { path: 'lb-search', loadChildren: './i-lesath-bottom/Pages/search/search.module#SearchPageModule' },
  // { path: 'lb-cart', loadChildren: './i-lesath-bottom/Pages/cart/cart.module#CartPageModule' },
  // { path: 'lb-my-order', loadChildren: './i-lesath-bottom/Pages/my-order/my-order.module#MyOrderPageModule' },
  // { path: 'lb-order-details', loadChildren: './i-lesath-bottom/Pages/order-details/order-details.module#OrderDetailsPageModule' },
  // { path: 'lb-wishlist', loadChildren: './i-lesath-bottom/Pages/wishlist/wishlist.module#WishlistPageModule' },
  // { path: 'lb-product-detail', loadChildren: './i-lesath-bottom/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'lb-shipping', loadChildren: './i-lesath-bottom/Pages/shipping/shipping.module#ShippingPageModule' },
  // { path: 'lb-filter', loadChildren: './i-lesath-bottom/Pages/filter/filter.module#FilterPageModule' },
  // { path: 'lb-image', loadChildren: './i-lesath-bottom/Pages/image/image.module#ImagePageModule' },
  // { path: 'lb-thank-you', loadChildren: './i-lesath-bottom/Pages/thank-you/thank-you.module#ThankYouPageModule' },
  // { path: 'lb-intro', loadChildren: './i-lesath-bottom/Pages/intro/intro.module#IntroPageModule' },
  // { path: 'lb-sub-category', loadChildren: './i-lesath-bottom/Pages/sub-category/sub-category.module#SubCategoryPageModule' },
  // { path: 'lb-color-theme', loadChildren: './i-lesath-bottom/Pages/color-theme/color-theme.module#ColorThemePageModule' },
  // { path: 'lb-privacy-policy', loadChildren: './i-lesath-bottom/Pages/privacy-policy/privacy-policy.module#PrivacyPolicyPageModule' },
  // { path: 'lb-refund-policy', loadChildren: './i-lesath-bottom/Pages/refund-policy/refund-policy.module#RefundPolicyPageModule' },
  // { path: 'lb-term-services', loadChildren: './i-lesath-bottom/Pages/term-services/term-services.module#TermServicesPageModule' },
  // { path: 'lb-news', loadChildren: './i-lesath-bottom/Pages/news/news.module#NewsPageModule' },
  // { path: 'lb-news-detail', loadChildren: './i-lesath-bottom/Pages/news-detail/news-detail.module#NewsDetailPageModule' },
  // { path: 'lb-account-info', loadChildren: './i-lesath-bottom/Pages/account-info/account-info.module#AccountInfoPageModule' },

  // //For rigel Side Paths
  // { path: 'ss-home', loadChildren: './i-rigel-side/Pages/home/home.module#HomePageModule' },
  // { path: 'ss-home-model', loadChildren: './i-rigel-side/Pages/home-model/home-model.module#HomeModelPageModule' },
  // { path: 'ss-category-detail', loadChildren: './i-rigel-side/Pages/category-detail/category-detail.module#CategoryDetailPageModule' },
  // { path: 'ss-product-sort', loadChildren: './i-rigel-side/Pages/product-sort/product-sort.module#ProductSortPageModule' },
  // { path: 'ss-product-size', loadChildren: './i-rigel-side/Pages/product-size/product-size.module#ProductSizePageModule' },
  // { path: 'ss-product-price', loadChildren: './i-rigel-side/Pages/product-price/product-price.module#ProductPricePageModule' },
  // { path: 'ss-product-color', loadChildren: './i-rigel-side/Pages/product-color/product-color.module#ProductColorPageModule' },
  // { path: 'ss-product-detail', loadChildren: './i-rigel-side/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'ss-product-detail-modal', loadChildren: './i-rigel-side/Pages/product-detail-modal/product-detail-modal.module#ProductDetailModalPageModule' },
  // { path: 'ss-review', loadChildren: './i-rigel-side/Pages/review/review.module#ReviewPageModule' },
  // { path: 'ss-my-account', loadChildren: './i-rigel-side/Pages/my-account/my-account.module#MyAccountPageModule' },
  // { path: 'ss-categories', loadChildren: './i-rigel-side/Pages/categories/categories.module#CategoriesPageModule' },
  // { path: 'ss-wishlist', loadChildren: './i-rigel-side/Pages/wishlist/wishlist.module#WishlistPageModule' },
  // { path: 'ss-cart', loadChildren: './i-rigel-side/Pages/cart/cart.module#CartPageModule' },
  // { path: 'ss-checkout', loadChildren: './i-rigel-side/Pages/checkout/checkout.module#CheckoutPageModule' },
  // { path: 'ss-thankyou', loadChildren: './i-rigel-side/Pages/thankyou/thankyou.module#ThankyouPageModule' },
  // { path: 'ss-login', loadChildren: './i-rigel-side/Pages/login/login.module#LoginPageModule' },
  // { path: 'ss-register', loadChildren: './i-rigel-side/Pages/register/register.module#RegisterPageModule' },
  // { path: 'ss-forget', loadChildren: './i-rigel-side/Pages/forget/forget.module#ForgetPageModule' },
  // { path: 'ss-my-order', loadChildren: './i-rigel-side/Pages/my-order/my-order.module#MyOrderPageModule' },
  // { path: 'ss-reward-points', loadChildren: './i-rigel-side/Pages/reward-points/reward-points.module#RewardPointsPageModule' },
  // { path: 'ss-my-addresses', loadChildren: './i-rigel-side/Pages/my-addresses/my-addresses.module#MyAddressesPageModule' },
  // { path: 'ss-news', loadChildren: './i-rigel-side/Pages/news/news.module#NewsPageModule' },
  // { path: 'ss-news-detail', loadChildren: './i-rigel-side/Pages/news-detail/news-detail.module#NewsDetailPageModule' },
  // { path: 'ss-intro', loadChildren: './i-rigel-side/Pages/intro/intro.module#IntroPageModule' },
  // { path: 'ss-contact-us', loadChildren: './i-rigel-side/Pages/contact-us/contact-us.module#ContactUsPageModule' },

  // // //For rigel Bottom
  // { path: 'sb-home', loadChildren: './i-rigel-bottom/Pages/home/home.module#HomePageModule' },
  // { path: 'sb-home-model', loadChildren: './i-rigel-bottom/Pages/home-model/home-model.module#HomeModelPageModule' },
  // { path: 'sb-category-detail', loadChildren: './i-rigel-bottom/Pages/category-detail/category-detail.module#CategoryDetailPageModule' },
  // { path: 'sb-product-sort', loadChildren: './i-rigel-bottom/Pages/product-sort/product-sort.module#ProductSortPageModule' },
  // { path: 'sb-product-size', loadChildren: './i-rigel-bottom/Pages/product-size/product-size.module#ProductSizePageModule' },
  // { path: 'sb-product-price', loadChildren: './i-rigel-bottom/Pages/product-price/product-price.module#ProductPricePageModule' },
  // { path: 'sb-product-color', loadChildren: './i-rigel-bottom/Pages/product-color/product-color.module#ProductColorPageModule' },
  // { path: 'sb-product-detail', loadChildren: './i-rigel-bottom/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'sb-product-detail-modal', loadChildren: './i-rigel-bottom/Pages/product-detail-modal/product-detail-modal.module#ProductDetailModalPageModule' },
  // { path: 'sb-my-account', loadChildren: './i-rigel-bottom/Pages/my-account/my-account.module#MyAccountPageModule' },
  // { path: 'sb-categories', loadChildren: './i-rigel-bottom/Pages/categories/categories.module#CategoriesPageModule' },
  // { path: 'sb-wishlist', loadChildren: './i-rigel-bottom/Pages/wishlist/wishlist.module#WishlistPageModule' },
  // { path: 'sb-cart', loadChildren: './i-rigel-bottom/Pages/cart/cart.module#CartPageModule' },
  // { path: 'sb-checkout', loadChildren: './i-rigel-bottom/Pages/checkout/checkout.module#CheckoutPageModule' },
  // { path: 'sb-thankyou', loadChildren: './i-rigel-bottom/Pages/thankyou/thankyou.module#ThankyouPageModule' },
  // { path: 'sb-login', loadChildren: './i-rigel-bottom/Pages/login/login.module#LoginPageModule' },
  // { path: 'sb-register', loadChildren: './i-rigel-bottom/Pages/register/register.module#RegisterPageModule' },
  // { path: 'sb-forget', loadChildren: './i-rigel-bottom/Pages/forget/forget.module#ForgetPageModule' },
  // { path: 'sb-my-order', loadChildren: './i-rigel-bottom/Pages/my-order/my-order.module#MyOrderPageModule' },
  // { path: 'sb-reward-points', loadChildren: './i-rigel-bottom/Pages/reward-points/reward-points.module#RewardPointsPageModule' },
  // { path: 'sb-my-addresses', loadChildren: './i-rigel-bottom/Pages/my-addresses/my-addresses.module#MyAddressesPageModule' },
  // { path: 'sb-news', loadChildren: './i-rigel-bottom/Pages/news/news.module#NewsPageModule' },
  // { path: 'sb-news-detail', loadChildren: './i-rigel-bottom/Pages/news-detail/news-detail.module#NewsDetailPageModule' },
  // { path: 'sb-intro', loadChildren: './i-rigel-bottom/Pages/intro/intro.module#IntroPageModule' },
  // { path: 'sb-contact-us', loadChildren: './i-rigel-bottom/Pages/contact-us/contact-us.module#ContactUsPageModule' },
  // { path: 'sb-news', loadChildren: './i-rigel-bottom/Pages/news/news.module#NewsPageModule' },
  // { path: 'sb-news-detail', loadChildren: './i-rigel-bottom/Pages/news-detail/news-detail.module#NewsDetailPageModule' },
  // { path: 'sb-review', loadChildren: './i-rigel-bottom/Pages/review/review.module#ReviewPageModule' },

  // // For Multipurpose Screens v1
  // { path: 'home-one', loadChildren: './home-one/home-one.module#HomeOnePageModule' },
  // { path: 'home-two', loadChildren: './home-two/home-two.module#HomeTwoPageModule' },
  // { path: 'home-three', loadChildren: './home-three/home-three.module#HomeThreePageModule' },
  // { path: 'home-four', loadChildren: './home-four/home-four.module#HomeFourPageModule' },
  // { path: 'home-five', loadChildren: './home-five/home-five.module#HomeFivePageModule' },
  // { path: 'home-six', loadChildren: './home-six/home-six.module#HomeSixPageModule' },
  // { path: 'home-seven', loadChildren: './home-seven/home-seven.module#HomeSevenPageModule' },
  // { path: 'home-eight', loadChildren: './home-eight/home-eight.module#HomeEightPageModule' },
  // { path: 'home-nine', loadChildren: './home-nine/home-nine.module#HomeNinePageModule' },
  // { path: 'home-ten', loadChildren: './home-ten/home-ten.module#HomeTenPageModule' },
  // { path: 'home-eleven', loadChildren: './home-eleven/home-eleven.module#HomeElevenPageModule' },
  // { path: 'categories-one', loadChildren: './categories-one/categories-one.module#CategoriesOnePageModule' },
  // { path: 'categories-two', loadChildren: './categories-two/categories-two.module#CategoriesTwoPageModule' },
  // { path: 'categories-three', loadChildren: './categories-three/categories-three.module#CategoriesThreePageModule' },
  // { path: 'categories-four', loadChildren: './categories-four/categories-four.module#CategoriesFourPageModule' },
  // { path: 'categories-five', loadChildren: './categories-five/categories-five.module#CategoriesFivePageModule' },
  // { path: 'categories-six', loadChildren: './categories-six/categories-six.module#CategoriesSixPageModule' },
  // { path: 'multipurpose-screens-details', loadChildren: './multipurpose-screens-details/multipurpose-screens-details.module#MultipurposeScreensDetailsPageModule' },
  // { path: 'signin-one', loadChildren: './signin-one/signin-one.module#SigninOnePageModule' },
  // { path: 'signin-two', loadChildren: './signin-two/signin-two.module#SigninTwoPageModule' },
  // { path: 'signup-one', loadChildren: './signup-one/signup-one.module#SignupOnePageModule' },
  // { path: 'signup-two', loadChildren: './signup-two/signup-two.module#SignupTwoPageModule' },
  // { path: 'forgot-pass-one', loadChildren: './forgot-pass-one/forgot-pass-one.module#ForgotPassOnePageModule' },
  // { path: 'forgot-pass-two', loadChildren: './forgot-pass-two/forgot-pass-two.module#ForgotPassTwoPageModule' },
  // { path: 'search-one', loadChildren: './search-one/search-one.module#SearchOnePageModule' },
  // { path: 'search-two', loadChildren: './search-two/search-two.module#SearchTwoPageModule' },
  // { path: 'intro-one', loadChildren: './intro-one/intro-one.module#IntroOnePageModule' },
  // { path: 'intro-two', loadChildren: './intro-two/intro-two.module#IntroTwoPageModule' },
  // { path: 'intro-three', loadChildren: './intro-three/intro-three.module#IntroThreePageModule' },
  // { path: 'product-detail-one', loadChildren: './product-detail-one/product-detail-one.module#ProductDetailOnePageModule' },
  // { path: 'product-detail-two', loadChildren: './product-detail-two/product-detail-two.module#ProductDetailTwoPageModule' },
  // { path: 'order-detail-one', loadChildren: './order-detail-one/order-detail-one.module#OrderDetailOnePageModule' },
  // { path: 'order-detail-two', loadChildren: './order-detail-two/order-detail-two.module#OrderDetailTwoPageModule' },
  // { path: 'cart-two', loadChildren: './cart-two/cart-two.module#CartTwoPageModule' },
  // { path: 'cart-one', loadChildren: './cart-one/cart-one.module#CartOnePageModule' },
  // { path: 'wishlist-one', loadChildren: './wishlist-one/wishlist-one.module#WishlistOnePageModule' },
  // { path: 'wishlist-two', loadChildren: './wishlist-two/wishlist-two.module#WishlistTwoPageModule' },
  // { path: 'thankyou-one', loadChildren: './thankyou-one/thankyou-one.module#ThankyouOnePageModule' },
  // { path: 'thankyou-two', loadChildren: './thankyou-two/thankyou-two.module#ThankyouTwoPageModule' },
  // { path: 'shop-two', loadChildren: './shop-two/shop-two.module#ShopTwoPageModule' },
  // { path: 'shop-one', loadChildren: './shop-one/shop-one.module#ShopOnePageModule' },
  // { path: 'home-twelve', loadChildren: './home-twelve/home-twelve.module#HomeTwelvePageModule' },
  // { path: 'categories-seven', loadChildren: './categories-seven/categories-seven.module#CategoriesSevenPageModule' },
  // { path: 'signin-three', loadChildren: './signin-three/signin-three.module#SigninThreePageModule' },
  // { path: 'signup-three', loadChildren: './signup-three/signup-three.module#SignupThreePageModule' },
  // { path: 'forget-pass-three', loadChildren: './forget-pass-three/forget-pass-three.module#ForgetPassThreePageModule' },
  // { path: 'intro-four', loadChildren: './intro-four/intro-four.module#IntroFourPageModule' },
  // { path: 'product-detail-three', loadChildren: './product-detail-three/product-detail-three.module#ProductDetailThreePageModule' },
  // { path: 'cart-three', loadChildren: './cart-three/cart-three.module#CartThreePageModule' },
  // { path: 'order-detail-three', loadChildren: './order-detail-three/order-detail-three.module#OrderDetailThreePageModule' },
  // { path: 'wishlist-three', loadChildren: './wishlist-three/wishlist-three.module#WishlistThreePageModule' },
  // { path: 'thankyou-three', loadChildren: './thankyou-three/thankyou-three.module#ThankyouThreePageModule' },
  // // For Multipurpose Screens v3
  // { path: 'aboutus-one', loadChildren: './aboutus-one/aboutus-one.module#AboutusOnePageModule' },
  // { path: 'cart-four', loadChildren: './cart-four/cart-four.module#CartFourPageModule' },
  // { path: 'cart-five', loadChildren: './cart-five/cart-five.module#CartFivePageModule' },
  // { path: 'cart-six', loadChildren: './cart-six/cart-six.module#CartSixPageModule' },
  // { path: 'cart-seven', loadChildren: './cart-seven/cart-seven.module#CartSevenPageModule' },
  // { path: 'news-one', loadChildren: './news-one/news-one.module#NewsOnePageModule' },
  // { path: 'news-two', loadChildren: './news-two/news-two.module#NewsTwoPageModule' },
  // { path: 'news-three', loadChildren: './news-three/news-three.module#NewsThreePageModule' },
  // { path: 'login-seven', loadChildren: './login-seven/login-seven.module#LoginSevenPageModule' },
  // { path: 'login-eight', loadChildren: './login-eight/login-eight.module#LoginEightPageModule' },
  // { path: 'login-nine', loadChildren: './login-nine/login-nine.module#LoginNinePageModule' },
  // { path: 'login-ten', loadChildren: './login-ten/login-ten.module#LoginTenPageModule' },
  // { path: 'login-eleven', loadChildren: './login-eleven/login-eleven.module#LoginElevenPageModule' },
  // { path: 'login-twelve', loadChildren: './login-twelve/login-twelve.module#LoginTwelvePageModule' },
  // { path: 'login-thirteen', loadChildren: './login-thirteen/login-thirteen.module#LoginThirteenPageModule' },
  // { path: 'login-fourteen', loadChildren: './login-fourteen/login-fourteen.module#LoginFourteenPageModule' },
  // { path: 'payment-one', loadChildren: './payment-one/payment-one.module#PaymentOnePageModule' },
  // { path: 'payment-two', loadChildren: './payment-two/payment-two.module#PaymentTwoPageModule' },
  // { path: 'search-five', loadChildren: './search-five/search-five.module#SearchFivePageModule' },
  // { path: 'search-six', loadChildren: './search-six/search-six.module#SearchSixPageModule' },
  // { path: 'setting-one', loadChildren: './setting-one/setting-one.module#SettingOnePageModule' },
  // { path: 'thankyou-four', loadChildren: './thankyou-four/thankyou-four.module#ThankyouFourPageModule' },
  // { path: 'thankyou-five', loadChildren: './thankyou-five/thankyou-five.module#ThankyouFivePageModule' },
  // { path: 'shopping-three', loadChildren: './shopping-three/shopping-three.module#ShoppingThreePageModule' },
  // { path: 'timeline-one', loadChildren: './timeline-one/timeline-one.module#TimelineOnePageModule' },
  // { path: 'chat-one', loadChildren: './chat-one/chat-one.module#ChatOnePageModule' },
  // { path: 'dashboard-one', loadChildren: './dashboard-one/dashboard-one.module#DashboardOnePageModule' },
  // { path: 'slider-one', loadChildren: './slider-one/slider-one.module#SliderOnePageModule' },
  // { path: 'slider-two', loadChildren: './slider-two/slider-two.module#SliderTwoPageModule' },
  // { path: 'audio-player-one', loadChildren: './audio-player-one/audio-player-one.module#AudioPlayerOnePageModule' },
  // { path: 'audio-player-two', loadChildren: './audio-player-two/audio-player-two.module#AudioPlayerTwoPageModule' },
  // { path: 'profile-one', loadChildren: './profile-one/profile-one.module#ProfileOnePageModule' },
  // { path: 'profile-two', loadChildren: './profile-two/profile-two.module#ProfileTwoPageModule' },
  // { path: 'verification-one', loadChildren: './verification-one/verification-one.module#VerificationOnePageModule' },
  // // For Multipurpose Screens v4
  // { path: 'register-seven', loadChildren: './register-seven/register-seven.module#RegisterSevenPageModule' },
  // { path: 'register-eight', loadChildren: './register-eight/register-eight.module#RegisterEightPageModule' },
  // { path: 'register-nine', loadChildren: './register-nine/register-nine.module#RegisterNinePageModule' },
  // { path: 'register-ten', loadChildren: './register-ten/register-ten.module#RegisterTenPageModule' },
  // { path: 'register-eleven', loadChildren: './register-eleven/register-eleven.module#RegisterElevenPageModule' },
  // { path: 'register-twelve', loadChildren: './register-twelve/register-twelve.module#RegisterTwelvePageModule' },
  // { path: 'register-thirteen', loadChildren: './register-thirteen/register-thirteen.module#RegisterThirteenPageModule' },
  // { path: 'register-fourteen', loadChildren: './register-fourteen/register-fourteen.module#RegisterFourteenPageModule' },
  // { path: 'forget-seven', loadChildren: './forget-seven/forget-seven.module#ForgetSevenPageModule' },
  // { path: 'forget-eight', loadChildren: './forget-eight/forget-eight.module#ForgetEightPageModule' },
  // { path: 'forget-nine', loadChildren: './forget-nine/forget-nine.module#ForgetNinePageModule' },
  // { path: 'forget-ten', loadChildren: './forget-ten/forget-ten.module#ForgetTenPageModule' },
  // { path: 'forget-eleven', loadChildren: './forget-eleven/forget-eleven.module#ForgetElevenPageModule' },
  // { path: 'forget-tweleve', loadChildren: './forget-tweleve/forget-tweleve.module#ForgetTwelevePageModule' },
  // { path: 'forget-thirteen', loadChildren: './forget-thirteen/forget-thirteen.module#ForgetThirteenPageModule' },
  // { path: 'forget-fourteen', loadChildren: './forget-fourteen/forget-fourteen.module#ForgetFourteenPageModule' },
  // { path: 'aboutus-two', loadChildren: './aboutus-two/aboutus-two.module#AboutusTwoPageModule' },
  // { path: 'aboutus-three', loadChildren: './aboutus-three/aboutus-three.module#AboutusThreePageModule' },
  // { path: 'aboutus-four', loadChildren: './aboutus-four/aboutus-four.module#AboutusFourPageModule' },
  // { path: 'aboutus-five', loadChildren: './aboutus-five/aboutus-five.module#AboutusFivePageModule' },
  // { path: 'aboutus-six', loadChildren: './aboutus-six/aboutus-six.module#AboutusSixPageModule' },
  // { path: 'aboutus-seven', loadChildren: './aboutus-seven/aboutus-seven.module#AboutusSevenPageModule' },
  // { path: 'aboutus-eight', loadChildren: './aboutus-eight/aboutus-eight.module#AboutusEightPageModule' },
  // { path: 'aboutus-nine', loadChildren: './aboutus-nine/aboutus-nine.module#AboutusNinePageModule' },
  // { path: 'aboutus-ten', loadChildren: './aboutus-ten/aboutus-ten.module#AboutusTenPageModule' },
  // { path: 'verification-two', loadChildren: './verification-two/verification-two.module#VerificationTwoPageModule' },
  // { path: 'verification-three', loadChildren: './verification-three/verification-three.module#VerificationThreePageModule' },
  // { path: 'verification-four', loadChildren: './verification-four/verification-four.module#VerificationFourPageModule' },
  // { path: 'verification-five', loadChildren: './verification-five/verification-five.module#VerificationFivePageModule' },
  // { path: 'verification-six', loadChildren: './verification-six/verification-six.module#VerificationSixPageModule' },
  // { path: 'verification-seven', loadChildren: './verification-seven/verification-seven.module#VerificationSevenPageModule' },
  // { path: 'verification-eight', loadChildren: './verification-eight/verification-eight.module#VerificationEightPageModule' },
  // { path: 'verification-nine', loadChildren: './verification-nine/verification-nine.module#VerificationNinePageModule' },
  // { path: 'verification-ten', loadChildren: './verification-ten/verification-ten.module#VerificationTenPageModule' },
  // // For Scripts
  // { path: 'scripts', loadChildren: './scripts-integrations/scripts/scripts.module#ScriptsPageModule' },
  // { path: 'social-login-integrations', loadChildren: './scripts-integrations/social-integrations/social-login-integrations/social-login-integrations.module#SocialLoginIntegrationsPageModule' },
   { path: 'google-map-integrations', loadChildren: './scripts-integrations/maps/google-map-integrations/google-map-integrations.module#GoogleMapIntegrationsPageModule' },
  // { path: 'sms-api-integrations', loadChildren: './scripts-integrations/sms-api-integrations/sms-api-integrations.module#SmsApiIntegrationsPageModule' },
  // { path: 'push-notification-integrations', loadChildren: './scripts-integrations/push-notification-integrations/push-notification-integrations.module#PushNotificationIntegrationsPageModule' },
  // { path: 'wordpress-posts', loadChildren: './scripts-integrations/wordpress/wordpress-posts/wordpress-posts.module#WordpressPostsPageModule' },
  // { path: 'wordpress-posts-details', loadChildren: './scripts-integrations/wordpress/wordpress-posts-details/wordpress-posts-details.module#WordpressPostsDetailsPageModule' },
  // { path: 'youtube-chanels', loadChildren: './scripts-integrations/youtube/youtube-chanels/youtube-chanels.module#YoutubeChanelsPageModule' },
  // { path: 'youtube-chanels-playlists', loadChildren: './scripts-integrations/youtube/youtube-chanels-playlists/youtube-chanels-playlists.module#YoutubeChanelsPlaylistsPageModule' },
  // { path: 'admob-integrations', loadChildren: './scripts-integrations/admobs/admob-integrations/admob-integrations.module#AdmobIntegrationsPageModule' },
  // // Payment Gateways Integration
  // { path: 'payment-integration', loadChildren: './scripts-integrations/payment-gateways/payment-integration/payment-integration.module#PaymentIntegrationPageModule' },
  // { path: 'braintree-method', loadChildren: './scripts-integrations/payment-gateways/braintree-method/braintree-method.module#BraintreeMethodPageModule' },
  // { path: 'paypal-method', loadChildren: './scripts-integrations/payment-gateways/paypal-method/paypal-method.module#PaypalMethodPageModule' },
  // { path: 'paystack-method', loadChildren: './scripts-integrations/payment-gateways/paystack-method/paystack-method.module#PaystackMethodPageModule' },
  // { path: 'razorpay-method', loadChildren: './scripts-integrations/payment-gateways/razorpay-method/razorpay-method.module#RazorpayMethodPageModule' },
  // { path: 'stripe-method', loadChildren: './scripts-integrations/payment-gateways/stripe-method/stripe-method.module#StripeMethodPageModule' },
  // Maps Integration
  { path: 'maps-integration', loadChildren: './scripts-integrations/maps/maps-integration/maps-integration.module#MapsIntegrationPageModule' },
  { path: 'here-map-integrations', loadChildren: './scripts-integrations/maps/here-map-integrations/here-map-integrations.module#HereMapIntegrationsPageModule' },
  // // Analytics Integration
  // { path: 'analytics-integration', loadChildren: './scripts-integrations/Analytics/analytics-integration/analytics-integration.module#AnalyticsIntegrationPageModule' },
  // { path: 'google-analytics', loadChildren: './scripts-integrations/Analytics/google-analytics/google-analytics.module#GoogleAnalyticsPageModule' },
  // { path: 'firebase-analytics', loadChildren: './scripts-integrations/Analytics/firebase-analytics/firebase-analytics.module#FirebaseAnalyticsPageModule' },
  // { path: 'flurry-analytics', loadChildren: './scripts-integrations/Analytics/flurry-analytics/flurry-analytics.module#FlurryAnalyticsPageModule' },
  // { path: 'cloud-storage', loadChildren: './scripts-integrations/cloud-storage-integrations/cloud-storage/cloud-storage.module#CloudStoragePageModule' },
  // { path: 'dropbox-integrationn', loadChildren: './scripts-integrations/cloud-storage-integrations/dropbox-integrations/dropbox-integrationn/dropbox-integrationn.module#DropboxIntegrationnPageModule' },
  // { path: 'woocomerce', loadChildren: './scripts-integrations/woocomerce-integrations/woocomerce/woocomerce.module#WoocomercePageModule' },
  // { path: 'woo-categories-detail', loadChildren: './scripts-integrations/woocomerce-integrations/woo-categories-detail/woo-categories-detail.module#WooCategoriesDetailPageModule' },
  // // { path: 'categories', loadChildren: './i-rigel-side/Pages/categories/categories.module#CategoriesPageModule' },
  // // { path: 'checkout', loadChildren: './i-rigel-side/Pages/checkout/checkout.module#CheckoutPageModule' },
  // // { path: 'checkout', loadChildren: './i-rigel-bottom/Pages/checkout/checkout.module#CheckoutPageModule' },
  // // { path: 'categories', loadChildren: './i-rigel-bottom/Pages/categories/categories.module#CategoriesPageModule' },
  // // { path: 'blank-modal', loadChildren: './src/app/EcommerceOne/Pages/blank-modal/blank-modal.module#BlankModalPageModule' },
  // // For Mini Apps
  // { path: 'mini-apps', loadChildren: './mini-apps/mini-apps.module#MiniAppsPageModule' },
  // // For News Mini Apps
  // { path: 'mini-news-one', loadChildren: './all-mini-apps/news/mini-news-one/mini-news-one.module#MiniNewsOnePageModule' },
  // { path: 'mini-news-two', loadChildren: './all-mini-apps/news/mini-news-two/mini-news-two.module#MiniNewsTwoPageModule' },
  // { path: 'mini-news-three', loadChildren: './all-mini-apps/news/mini-news-three/mini-news-three.module#MiniNewsThreePageModule' },
  // { path: 'mini-news-detail-one', loadChildren: './all-mini-apps/news/mini-news-detail-one/mini-news-detail-one.module#MiniNewsDetailOnePageModule' },
  // { path: 'mini-news-detail-two', loadChildren: './all-mini-apps/news/mini-news-detail-two/mini-news-detail-two.module#MiniNewsDetailTwoPageModule' },
  // { path: 'mini-news-detail-three', loadChildren: './all-mini-apps/news/mini-news-detail-three/mini-news-detail-three.module#MiniNewsDetailThreePageModule' },
  // // For Lesath Mini App
  // { path: 'mini-lesath-cart', loadChildren: './all-mini-apps/lesath/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-lesath-home', loadChildren: './all-mini-apps/lesath/Pages/home-pages/home/home.module#HomePageModule' },
  // { path: 'mini-lesath-product-detail/:id', loadChildren: './all-mini-apps/lesath/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // //For Becrux Mini Apps
  // // For Becrux One
  // { path: 'mini-becrux-one-cart', loadChildren: './all-mini-apps/becrux/becrux-one/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-one-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-one/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-one-home', loadChildren: './all-mini-apps/becrux/becrux-one/Pages/home/home.module#HomePageModule' },
  // // For Bexrux Two
  // { path: 'mini-becrux-two-cart', loadChildren: './all-mini-apps/becrux/becrux-two/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-two-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-two/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-two-home', loadChildren: './all-mini-apps/becrux/becrux-two/Pages/home/home.module#HomePageModule' },
  // // For Becrux Three
  // { path: 'mini-becrux-three-cart', loadChildren: './all-mini-apps/becrux/becrux-three/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-three-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-three/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-three-home', loadChildren: './all-mini-apps/becrux/becrux-three/Pages/home/home.module#HomePageModule' },
  // // For Becrux Four
  // { path: 'mini-becrux-four-cart', loadChildren: './all-mini-apps/becrux/becrux-four/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-four-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-four/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-four-home', loadChildren: './all-mini-apps/becrux/becrux-four/Pages/home/home.module#HomePageModule' },
  // // For Becrux Five
  // { path: 'mini-becrux-five-cart', loadChildren: './all-mini-apps/becrux/becrux-five/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-five-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-five/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-five-home', loadChildren: './all-mini-apps/becrux/becrux-five/Pages/home/home.module#HomePageModule' },
  // // For Becrux Six
  // { path: 'mini-becrux-six-cart', loadChildren: './all-mini-apps/becrux/becrux-six/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-six-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-six/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-six-home', loadChildren: './all-mini-apps/becrux/becrux-six/Pages/home/home.module#HomePageModule' },
  // // For Becrux Seven
  // { path: 'mini-becrux-seven-cart', loadChildren: './all-mini-apps/becrux/becrux-seven/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-seven-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-seven/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-seven-home', loadChildren: './all-mini-apps/becrux/becrux-seven/Pages/home/home.module#HomePageModule' },
  // // For Becrux Eight
  // { path: 'mini-becrux-eight-cart', loadChildren: './all-mini-apps/becrux/becrux-eight/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-eight-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-eight/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-eight-home', loadChildren: './all-mini-apps/becrux/becrux-eight/Pages/home/home.module#HomePageModule' },
  // // For Becrux Nine
  // { path: 'mini-becrux-nine-cart', loadChildren: './all-mini-apps/becrux/becrux-nine/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-nine-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-nine/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-nine-home', loadChildren: './all-mini-apps/becrux/becrux-nine/Pages/home/home.module#HomePageModule' },
  // // For Becrux Ten
  // { path: 'mini-becrux-ten-cart', loadChildren: './all-mini-apps/becrux/becrux-ten/Pages/cart/cart.module#CartPageModule' },
  // { path: 'mini-becrux-ten-product-detail/:id', loadChildren: './all-mini-apps/becrux/becrux-ten/Pages/product-detail/product-detail.module#ProductDetailPageModule' },
  // { path: 'mini-becrux-ten-home', loadChildren: './all-mini-apps/becrux/becrux-ten/Pages/home/home.module#HomePageModule' },
];
@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
